development:
  clients:
    default:
      database: url_shortener_owarbv_dev
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
test:
  clients:
    default:
      database: url_shortener_owarbv_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
